# Generated by Django 5.1.6 on 2025-02-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Affairs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="is_completed",
            field=models.BooleanField(
                choices=[(True, "Выполнена"), (False, "Не выполнена")],
                default=False,
                verbose_name="Задача выполнена?",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="tags",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Urgent", "Срочная"),
                    ("On control", "На контроле"),
                    ("Waiting", "В ожидании"),
                    ("For discussion", "На обсуждение"),
                    ("In progress", "В процессе"),
                ],
                max_length=50,
                null=True,
                verbose_name="Теги",
            ),
        ),
    ]
